

drop database USUARIOS


create database USUARIOS

use USUARIOS

CREATE TABLE ROLES (  
  ID_ROLE int NOT NULL IDENTITY(1,1) PRIMARY KEY ,  
  ROL varchar(255) NOT NULL,  
) 
  
CREATE TABLE USUARIOS (  
  ID_USUARIO int NOT NULL IDENTITY(1,1) PRIMARY KEY,  
  USERNAME varchar(255) NOT NULL,  
  PASSWORD varchar(255) NOT NULL,  
) 
  
CREATE TABLE USER_ROL ( 
    ID_USUARIO INT NOT NULL REFERENCES  USUARIOS(ID_USUARIO),
    ID_ROLE INT NOT NULL REFERENCES ROLES(ID_ROLE),
    PRIMARY KEY (ID_USUARIO,ID_ROLE)
);