

drop database USUARIOS


create database USUARIOS

use USUARIOS

CREATE TABLE USUARIO (
    USER_ID INT PRIMARY KEY IDENTITY(1,1),
    USERNAME VARCHAR(100) NOT NULL ,
    PASSWORD VARCHAR(100) NOT NULL, 
   
 );

 CREATE TABLE ROL (
    ROL VARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(100)
);



CREATE TABLE USUARIOS (
    USER_ID INT PRIMARY KEY IDENTITY(1,1),
    USERNAME VARCHAR(100) NOT NULL ,
    PASSWORD VARCHAR(100) NOT NULL, 
    ENABLED BIT NOT NULL ,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FECHA_NACIMIENTO DATE, 
    SEXO VARCHAR(1),
     CHECK (SEXO in ('F','M'))
 );


CREATE TABLE ROLES (  
  ID_ROLE int NOT NULL IDENTITY(1,1) PRIMARY KEY ,  
  ROL varchar(255) NOT NULL,  
) 
  
CREATE TABLE USUARIOS (  
  ID_USUARIO int NOT NULL IDENTITY(1,1) PRIMARY KEY,  
  USERNAME varchar(255) NOT NULL,  
  PASSWORD varchar(255) NOT NULL,  
) 
  
CREATE TABLE USER_ROL ( 
    ID_USUARIO INT NOT NULL REFERENCES  USUARIOS(ID_USUARIO),
    ID_ROLE INT NOT NULL REFERENCES ROLES(ID_ROLE),
    PRIMARY KEY (ID_USUARIO,ID_ROLE)
);