use USUARIOS

INSERT INTO USUARIOS (PASSWORD, USERNAME) VALUES (123, 'A')
INSERT INTO USUARIOS (PASSWORD, USERNAME) VALUES (123, 'B')
INSERT INTO USUARIOS (PASSWORD, USERNAME) VALUES (123, 'C')
INSERT INTO USUARIOS (PASSWORD, USERNAME) VALUES (123, 'D')
INSERT INTO ROLES(ROL) VALUES ('ROLE_USER')
INSERT INTO ROLES(ROL) VALUES ('ROLE_ADMIN')
INSERT INTO USER_ROL (ID_ROLE,ID_USUARIO) VALUES (1,1)
INSERT INTO USER_ROL (ID_ROLE,ID_USUARIO) VALUES (2,2)
INSERT INTO USER_ROL (ID_ROLE,ID_USUARIO) VALUES (1,3)
INSERT INTO USER_ROL (ID_ROLE,ID_USUARIO) VALUES (2,4)

